version: '2'
services:
  shopfront:
    image: vedg/djshopfront
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: vedg/productcatalogue
    ports:
     - "8020:8020"
  stockmanager:
    image: vedg/stockmanager
    ports:
     - "8030:8030"
